### ISSUE TITLE
Gitter link is broken 

### ISSUE THREAD

**Issue by jmolivas** [nilportugues/symfony-hal-json#2]
the gitter link is broken `https://gitter.im/nilportugues/symfony2-haljson-transformer` I tried with  `https://gitter.im/nilportugues/symfony2-hal-json-transformer` with no luck, maybe the chat is not created already.

![gitter-symfony-hal-json](https://cloud.githubusercontent.com/assets/366275/9446652/9f0307a6-4a47-11e5-9672-892ca7f88c81.png)

**Comment by nilportugues** [comment]
Thanks, i totally missed it! https://gitter.im/nilportugues/symfony2-hal-json-transformer :+1:  is ready now :)
